version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 9005:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/db/mysql:/var/lib/mysql

  adminer:
    image: dehy/adminer
    restart: always
    ports:
      - 9080:80